package entities;
// Generated Jun 3, 2017 12:46:50 AM by Hibernate Tools 4.3.1



/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer idschedule;
     private String cabinet;
     private String speciality;
     private String name;
     private String groupId;
     private String monday;
     private String tuesday;
     private String wednesday;
     private String thursday;
     private String friday;
     private String saturday;
     private String sunday;

    public Schedule() {
    }

    public Schedule(String cabinet, String speciality, String name, String groupId, String monday, String tuesday, String wednesday, String thursday, String friday, String saturday, String sunday) {
       this.cabinet = cabinet;
       this.speciality = speciality;
       this.name = name;
       this.groupId = groupId;
       this.monday = monday;
       this.tuesday = tuesday;
       this.wednesday = wednesday;
       this.thursday = thursday;
       this.friday = friday;
       this.saturday = saturday;
       this.sunday = sunday;
    }
   
    public Integer getIdschedule() {
        return this.idschedule;
    }
    
    public void setIdschedule(Integer idschedule) {
        this.idschedule = idschedule;
    }
    public String getCabinet() {
        return this.cabinet;
    }
    
    public void setCabinet(String cabinet) {
        this.cabinet = cabinet;
    }
    public String getSpeciality() {
        return this.speciality;
    }
    
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getMonday() {
        return this.monday;
    }
    
    public void setMonday(String monday) {
        this.monday = monday;
    }
    public String getTuesday() {
        return this.tuesday;
    }
    
    public void setTuesday(String tuesday) {
        this.tuesday = tuesday;
    }
    public String getWednesday() {
        return this.wednesday;
    }
    
    public void setWednesday(String wednesday) {
        this.wednesday = wednesday;
    }
    public String getThursday() {
        return this.thursday;
    }
    
    public void setThursday(String thursday) {
        this.thursday = thursday;
    }
    public String getFriday() {
        return this.friday;
    }
    
    public void setFriday(String friday) {
        this.friday = friday;
    }
    public String getSaturday() {
        return this.saturday;
    }
    
    public void setSaturday(String saturday) {
        this.saturday = saturday;
    }
    public String getSunday() {
        return this.sunday;
    }
    
    public void setSunday(String sunday) {
        this.sunday = sunday;
    }




}


